version: '3.7'

services:

  redis:
    image: library/redis
    networks:
      - redis

  phpderedis:
    image: issammartos/phpredis:latest
    restart: always
    ports: 
      - "8888:80"
    networks:
      - redis
    depends_on:
      - redis

networks:
  redis:
    external: true

